
package com.github.developermobile.sistemadevendas.view;

import com.github.developermobile.sistemadevendas.domain.entities.ItensVenda;
import com.github.developermobile.sistemadevendas.domain.entities.Venda;
import com.github.developermobile.sistemadevendas.domain.exceptions.DAOExceptions;
import com.github.developermobile.sistemadevendas.domain.service.VendaService;
import com.github.developermobile.sistemadevendas.utils.FormatterUtils;
import com.github.developermobile.sistemadevendas.utils.JOPUtil;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiago
 */
public class ConsultaVendaFrame extends javax.swing.JInternalFrame {
    private DefaultTableModel dtmVenda;
    private DefaultTableModel dtmItensVenda;
    private ListSelectionModel listModel;
    
    private List<Venda> vendas;
    private List<ItensVenda> itensVendas;
  
    public ConsultaVendaFrame() {
        initComponents();
        defineModelo();
    }
    
    private void defineModelo() {
        dtmVenda = (DefaultTableModel) tbVenda.getModel();
        dtmItensVenda = (DefaultTableModel) tbItensVenda.getModel();
        listModel = tbVenda.getSelectionModel();
        listModel.addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting()) {
                mostraDetalhe();
            }
        });
        
        FormatterUtils.maskFormatterData("##/##/####", ftfDataInicio);
        FormatterUtils.maskFormatterData("##/##/####", ftfDataFim);
        
        tbItensVenda.getColumnModel().getColumn(0).setPreferredWidth(400);
        tbVenda.getColumnModel().getColumn(1).setPreferredWidth(300);
    }
    
    private void mostraDetalhe() {
        if (tbVenda.getSelectedRow() != -1) {
            itensVendas = vendas.get(tbVenda.getSelectedRow()).getItensVendas();
            removeItensVenda();
            
            for (int i = 0; i < itensVendas.size(); i++) {
                dtmItensVenda.insertRow(i, new Object[] {
                    itensVendas.get(i).getId().getProduto().getNome(),
                    itensVendas.get(i).getQtde(),
                    itensVendas.get(i).getId().getProduto().getValor(),
                    itensVendas.get(i).total()
                });
            }
        } else {
             removeItensVenda();
        }
    }
    
    private void removeItensVenda() {
        int linha = tbItensVenda.getRowCount();
        
        for (int i = 0; i < linha; i++) {
            dtmItensVenda.removeRow(0);
        }
    }
    
    private void atualizaTabela() {
         DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try {
            LocalDate inicio = LocalDate.parse(ftfDataInicio.getText(), fmt);
            LocalDate fim = LocalDate.parse(ftfDataFim.getText(), fmt);
            vendas = VendaService.getInstance().findByData(inicio, fim);
            
            int linha = tbVenda.getRowCount();
            
            for (int i = 0; i < linha; i++) {
                dtmVenda.removeRow(0);
            }
            
            
            for (int i = 0; i < vendas.size(); i++) {
                dtmVenda.insertRow(i, new Object[] { 
                    vendas.get(i).getId(),
                    vendas.get(i).getCliente().getNome(),
                    vendas.get(i).getDataVenda().format(fmt)
                });
            }
        } catch (DAOExceptions e) {
            JOPUtil.message(e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void pesquisaVendas() {
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbDataFim = new javax.swing.JPanel();
        lbDataInicio = new javax.swing.JLabel();
        ftfDataInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        ftfDataFim = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenda = new javax.swing.JTable();
        lbItensVenda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbItensVenda = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Vendas");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 119, 0));
        jPanel1.setLayout(new java.awt.FlowLayout(0));

        lbTitle.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("Consulta de Vendas");
        jPanel1.add(lbTitle);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        lbDataFim.setLayout(new java.awt.GridBagLayout());

        lbDataInicio.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lbDataInicio.setText("Data Inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        lbDataFim.add(lbDataInicio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        lbDataFim.add(ftfDataInicio, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Data Fim:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        lbDataFim.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        lbDataFim.add(ftfDataFim, gridBagConstraints);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        lbDataFim.add(btnPesquisar, gridBagConstraints);

        tbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Data Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        lbDataFim.add(jScrollPane1, gridBagConstraints);

        lbItensVenda.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lbItensVenda.setText("Itens da Venda:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        lbDataFim.add(lbItensVenda, gridBagConstraints);

        tbItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Qtde", "Vlr. Unit.", "Vlr. Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbItensVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        lbDataFim.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(lbDataFim, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
      pesquisaVendas();
    }//GEN-LAST:event_btnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JFormattedTextField ftfDataFim;
    private javax.swing.JFormattedTextField ftfDataInicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lbDataFim;
    private javax.swing.JLabel lbDataInicio;
    private javax.swing.JLabel lbItensVenda;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTable tbItensVenda;
    private javax.swing.JTable tbVenda;
    // End of variables declaration//GEN-END:variables
}
