package com.github.developermobile.sistemadevendas.view;


import com.github.developermobile.sistemadevendas.utils.DesktopPanelImage;
import com.github.developermobile.sistemadevendas.utils.FrameUtil;
import com.github.developermobile.sistemadevendas.utils.JOPUtil;
import com.github.developermobile.sistemadevendas.utils.KeyboardUtil;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author tiago
 */
public class Main extends javax.swing.JFrame {
    DesktopPanelImage desktopPane = new DesktopPanelImage(getClass().getResource("/images/logo_app.png"));

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        KeyboardUtil.nextFocusEnter(this); 
        this.add(desktopPane, "card1");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mnSistema = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();
        mnCadastro = new javax.swing.JMenu();
        miCliente = new javax.swing.JMenuItem();
        miFornecedor = new javax.swing.JMenuItem();
        miProduto = new javax.swing.JMenuItem();
        mnVendas = new javax.swing.JMenu();
        miRegistrarVenda = new javax.swing.JMenuItem();
        miConsultarVenda = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        miSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sitema de Vendas");
        setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new java.awt.CardLayout());

        mnSistema.setMnemonic('S');
        mnSistema.setText("Sistema");

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mnSistema.add(miSair);

        menuBar.add(mnSistema);

        mnCadastro.setMnemonic('C');
        mnCadastro.setText("Cadastro");

        miCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        miCliente.setText("Cliente");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        mnCadastro.add(miCliente);

        miFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        miFornecedor.setText("Fornecedor");
        miFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFornecedorActionPerformed(evt);
            }
        });
        mnCadastro.add(miFornecedor);

        miProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        miProduto.setText("Produto");
        miProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProdutoActionPerformed(evt);
            }
        });
        mnCadastro.add(miProduto);

        menuBar.add(mnCadastro);

        mnVendas.setMnemonic('V');
        mnVendas.setText("Vendas");

        miRegistrarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        miRegistrarVenda.setText("Registrar Venda");
        miRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistrarVendaActionPerformed(evt);
            }
        });
        mnVendas.add(miRegistrarVenda);

        miConsultarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        miConsultarVenda.setText("Consultar Venda");
        mnVendas.add(miConsultarVenda);

        menuBar.add(mnVendas);

        mnAjuda.setText("Ajuda");

        miSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miSobre.setText("Sobre");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        mnAjuda.add(miSobre);

        menuBar.add(mnAjuda);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
           JOPUtil.message(
                "Sistema de Vendas - tiago.pereira.vieira@gmail.com", 
                "Informação", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miSobreActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        int option = JOPUtil.confirmMessage(
                "Deseja sair do sistema?", 
                "Sair do sistema", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE);
                
                if (option == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
    }//GEN-LAST:event_miSairActionPerformed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
       FrameUtil.abreInternalFrame(desktopPane, new ClienteFrame(), this);
    }//GEN-LAST:event_miClienteActionPerformed

    private void miFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFornecedorActionPerformed
       FrameUtil.abreInternalFrame(desktopPane, new FornecedorFrame(), this);
    }//GEN-LAST:event_miFornecedorActionPerformed

    private void miProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProdutoActionPerformed
       FrameUtil.abreInternalFrame(desktopPane, new ProdutoFrame(), this);
    }//GEN-LAST:event_miProdutoActionPerformed

    private void miRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistrarVendaActionPerformed
        FrameUtil.abreInternalFrame(desktopPane, new VendaFrame(), this);
    }//GEN-LAST:event_miRegistrarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miConsultarVenda;
    private javax.swing.JMenuItem miFornecedor;
    private javax.swing.JMenuItem miProduto;
    private javax.swing.JMenuItem miRegistrarVenda;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miSobre;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenu mnVendas;
    // End of variables declaration//GEN-END:variables
}
